flags:
    binary-serialise-cbor:
        newtime15: true
packages:
- ./hs-invoke
- ./hs-invoke-bin
- ../../binary-serialise-cbor
- ../../distributed-closure
- ../../distributed-closure/vendor/binary
extra-deps: []
resolver: nightly-2015-11-09
