flags:
    binary-serialise-cbor:
        newtime15: true
packages:
- simple-spark-app/hs-invoke
- simple-spark-app/hs-invoke-bin
- java-to-haskell
- location:
    git: git@github.com:well-typed/binary-serialise-cbor
    commit: 992e2c758f9b5795390208ecea162a6ad0166ce6
extra-deps:
- distributed-closure-0.1.0.0
- binary-0.7.6.1
resolver: nightly-2015-12-09
nix:
    shell-file: shell.nix
