require-stack-version: ">= 1.4"

resolver: lts-10.0

packages:
- .
- apps/argv
- apps/bench
- apps/dataframe
- apps/hello
- apps/lda
- apps/rdd-ops

extra-deps:
- jvm-streaming-0.2.2

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]

docker:
  enable: false
  image: tweag/sparkle
  run-args: ["--net=bridge"]
  stack-exe: image
