flags:
   binary-serialise-cbor:
       newtime15: true
packages:
- spark
- examples/hello
- examples/lda
- location:
    git: git@github.com:well-typed/binary-serialise-cbor
    commit: 992e2c758f9b5795390208ecea162a6ad0166ce6
extra-deps:
- distributed-closure-0.1.0.0
- binary-0.7.6.1
resolver: nightly-2015-12-09
nix:
    shell-file: shell.nix
