packages:
- inline-java
- sparkle
- apps/hello
- apps/lda
- apps/rdd-ops
- location:
    git: git@github.com:tweag/distributed-closure
    commit: 565c4da9b4706407b209aa7ebc896fd79ccd651d
  extra-dep: true
resolver: lts-5.1
extra-deps:
- thread-local-storage-0.1.0.3
nix:
  enable: false
  shell-file: shell.nix
