packages:
- .
- inline-java
- apps/hello
- apps/lda
- apps/rdd-ops
resolver: lts-5.1
extra-deps:
- thread-local-storage-0.1.0.3
- distributed-closure-0.3.0.0
nix:
  enable: false
  shell-file: shell.nix
