packages:
- sparkle
- apps/hello
- apps/lda
- location:
    git: git@github.com:tweag/distributed-closure
    commit: a0055dc39fe6d9cf2829786808b7ef6ecf3ed107
  extra-dep: true
resolver: lts-5.1
extra-deps:
- thread-local-storage-0.1.0.3
nix:
  enable: false
  shell-file: shell.nix
