flags:
   binary-serialise-cbor:
       newtime15: true
packages:
- sparkle
- examples/hello
- examples/lda
- location:
    git: git@github.com:well-typed/binary-serialise-cbor
    commit: 992e2c758f9b5795390208ecea162a6ad0166ce6
extra-deps:
- distributed-closure-0.2.1.0
resolver: lts-5.1
nix:
    shell-file: shell.nix
