steps:
  - label: "Build and test with bazel"
    command:
      - echo "build --host_platform=@rules_haskell//haskell/platforms:linux_x86_64_nixpkgs" > .bazelrc.local
      - nix-shell --pure --run 'bazel build //...'
      - nix-shell --pure --run 'bazel build //apps/hello:sparkle-example-hello_deploy.jar'
      - nix-shell --pure --run 'bazel run spark-submit -- $PWD/bazel-bin/apps/hello/sparkle-example-hello_deploy.jar $PWD/apps/hello/lorem-ipsum.txt'
    timeout: 60
    depends_on: "build-packages-bazel"
  - label: "Build and test with stack"
    command:
      - nix-shell --pure --run 'stack --no-terminal --nix build --pedantic'
      - nix-shell --pure --run 'stack --no-terminal --nix exec -- sparkle package sparkle-example-hello'
      - nix-shell --pure --run 'stack --no-terminal --nix exec -- spark-submit sparkle-example-hello.jar apps/hello/lorem-ipsum.txt'
    timeout: 120
