/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_tweag_sparkle_Sparkle */

#ifndef _Included_io_tweag_sparkle_Sparkle
#define _Included_io_tweag_sparkle_Sparkle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_tweag_sparkle_Sparkle
 * Method:    sparkMain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_tweag_sparkle_Sparkle_sparkMain
  (JNIEnv *, jclass);

/*
 * Class:     io_tweag_sparkle_Sparkle
 * Method:    initializeHaskellRTS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_tweag_sparkle_Sparkle_initializeHaskellRTS
  (JNIEnv *, jclass);

/*
 * Class:     io_tweag_sparkle_Sparkle
 * Method:    finalizeHaskellRTS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_tweag_sparkle_Sparkle_finalizeHaskellRTS
  (JNIEnv *, jclass);

/*
 * Class:     io_tweag_sparkle_Sparkle
 * Method:    apply
 * Signature: ([B[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_tweag_sparkle_Sparkle_apply
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

/*
 * Class:     io_tweag_sparkle_Sparkle
 * Method:    invoke
 * Signature: ([B[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_io_tweag_sparkle_Sparkle_invoke
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
