/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HaskellRTS */

#ifndef _Included_HaskellRTS
#define _Included_HaskellRTS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HaskellRTS
 * Method:    sparkMain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HaskellRTS_sparkMain
  (JNIEnv *, jclass);

/*
 * Class:     HaskellRTS
 * Method:    hask_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HaskellRTS_hask_1init
  (JNIEnv *, jclass);

/*
 * Class:     HaskellRTS
 * Method:    hask_end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HaskellRTS_hask_1end
  (JNIEnv *, jclass);

/*
 * Class:     HaskellRTS
 * Method:    invoke
 * Signature: ([BLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_HaskellRTS_invoke
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
