name: Build & test
on:
  push:
env:
  BAZEL_ARGS: --repository_cache=/Users/runner/repo-cache --disk_cache=/Users/runner/disk-cache

jobs:
  test:
    name: Run test
    runs-on: macos-11
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NixOS
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=./nixpkgs.nix

      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: tweag

      - name: Run cachix
        run: cachix watch-store tweag &

      - name: Configure
        run: mkdir -p ~/repo-cache ~/disk-cache

      - name: Prefetch Stackage snapshot
        run: nix-shell --pure --run "cmd='bazel fetch @stackage//... $BAZEL_ARGS'; \$cmd || \$cmd || \$cmd"

      - name: Build all
        run: |
          while true; do echo "."; sleep 60; done &
          nix-shell --pure --run "bazel build //apps/hello:sparkle-example-hello_deploy.jar $BAZEL_ARGS"
          nix-shell --pure --run "bazel build //apps/rdd-ops:sparkle-example-rddops_deploy.jar $BAZEL_ARGS"
          nix-shell --pure --run "bazel build //apps/osthreads:sparkle-example-osthreads_deploy.jar $BAZEL_ARGS"

      - name: Install Apache Spark and Hadoop
        uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.3.1'
          spark-url: 'https://downloads.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-without-hadoop.tgz'
          hadoop-version: '2.10.1'

      - name: Run tests
        run: spark-submit --packages com.amazonaws:aws-java-sdk:1.11.920,org.apache.hadoop:hadoop-aws:2.10.1 bazel-bin/apps/hello/sparkle-example-hello_deploy.jar
