name: Build & test
on:
  push:
env:
  BAZEL_ARGS: --repository_cache=~/repo-cache --disk_cache=~/disk-cache

jobs:
  test:
    name: Run test
    runs-on: macos-11
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NixOS
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=./nixpkgs.nix

      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: tweag

      - name: Run cachix
        run: cachix watch-store tweag &

      - name: Configure
        run: mkdir -p ~/repo-cache ~/disk-cache

      - name: Prefetch Stackage snapshot
        run: nix-shell --pure --run "cmd='bazel fetch @stackage//... $BAZEL_ARGS'; \$cmd || \$cmd || \$cmd"

      - name: Build all
        run: |
          while true; do echo "."; sleep 60; done &
          nix-shell --pure --run "bazel build //apps/hello:sparkle-example-hello_deploy.jar $BAZEL_ARGS"
          nix-shell --pure --run "bazel build //apps/rdd-ops:sparkle-example-rddops_deploy.jar $BAZEL_ARGS"
          nix-shell --pure --run "bazel build //apps/osthreads:sparkle-example-osthreads_deploy.jar $BAZEL_ARGS"

      - name: Install Apache Spark and Hadoop
        run: |
          curl -OL https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
          curl -OL https://downloads.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop2.tgz
          tar -xzf spark-3.3.1-bin-hadoop3.tgz
          curl -OL https://downloads.apache.org/hadoop/hadoop-3.3.1/hadoop-3.3.1.tgz
          tar -xzf hadoop-3.3.1.tgz

      - name: Run tests
        run: |
          export SPARK_DIST_CLASSPATH=$PWD/slf4j-api-1.7.30.jar:$(hadoop-3.3.1/bin/hadoop classpath)
          export PATH="$PWD/spark-3.3.1-bin-hadoop2/bin:$PATH"
          # Remove quarantine flags from executables to avoid getting killed with a signal 9
          # See https://github.com/dotnet/spark/blob/main/docs/getting-started/macos-instructions.md
          xattr -d com.apple.quarantine spark-3.3.1-bin/hadoop2/bin/*
          spark-submit --packages com.amazonaws:aws-java-sdk:1.11.920,org.apache.hadoop:hadoop-aws:3.3.1 bazel-bin/apps/hello/sparkle-example-hello_deploy.jar
