name: Build & test
on:
  push:
env:
  BAZEL_ARGS: --repository_cache=/Users/runner/repo-cache --disk_cache=/Users/runner/disk-cache

jobs:
  test:
    name: Run test
    runs-on: macos-11
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NixOS
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=./nixpkgs.nix

      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: tweag

      - name: Run cachix
        run: cachix watch-store tweag &

      - name: Configure
        run: mkdir -p ~/repo-cache ~/disk-cache

      - name: Prefetch Stackage snapshot
        run: nix-shell --pure --run "cmd='bazel fetch @stackage//... $BAZEL_ARGS'; \$cmd || \$cmd || \$cmd"

      - name: Build all
        run: |
          while true; do echo "."; sleep 60; done &
          nix-shell --pure --run "bazel build //apps/hello:sparkle-example-hello_deploy.jar $BAZEL_ARGS"
          nix-shell --pure --run "bazel build //apps/rdd-ops:sparkle-example-rddops_deploy.jar $BAZEL_ARGS"
          nix-shell --pure --run "bazel build //apps/osthreads:sparkle-example-osthreads_deploy.jar $BAZEL_ARGS"

      - name: Install spark and hadoop
        run: |
          curl -OL https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
          curl -OL https://downloads.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-without-hadoop.tgz
          tar -xzf spark-3.3.1-bin-without-hadoop.tgz
          curl -OL https://downloads.apache.org/hadoop/common/hadoop-2.10.1/hadoop-2.10.1.tar.gz
          tar -xzf hadoop-2.10.1.tar.gz

      - name: Run tests
        run: |
          export SPARK_DIST_CLASSPATH=$PWD/slf4j-api-1.7.30.jar:$(hadoop-2.10.1/bin/hadoop classpath)
          export LD_LIBRARY_PATH=$PWD/hadoop-2.10.1/lib/native
          export PATH="$PWD/spark-3.3.1-bin-without-hadoop/bin:$PATH"
          spark-submit --packages com.amazonaws:aws-java-sdk:1.11.920,org.apache.hadoop:hadoop-aws:2.10.1 bazel-bin/apps/hello/sparkle-example-hello_deploy.jar
